# Convert docker commands to aliasies directly
alias dattach="docker attach"
alias dbuild="docker build"
alias dcommit="docker commit"
alias dcp="docker cp"
alias dcreate="docker create"
alias ddiff="docker diff"
alias devents="docker events"
alias dexec="docker exec"
alias dexport="docker export"
alias dhistory="docker history"
alias dimages="docker images"
alias dimport="docker import"
alias dinfo="docker info"
alias dinspect="docker inspect"
alias dkill="docker kill"
alias dload="docker load"
alias dlogin="docker login"
alias dlogout="docker logout"
alias dlogs="docker logs"
alias dport="docker port"
alias dpause="docker pause"
alias dps="docker ps"
alias dpull="docker pull"
alias dpush="docker push"
alias drename="docker rename"
alias drestart="docker restart"
alias drm="docker rm"
alias drmi="docker rmi"
alias drun="docker run"
alias dsave="docker save"
alias dsearch="docker search"
alias dstart="docker start"
alias dstats="docker stats"
alias dstop="docker stop"
alias dtag="docker tag"
alias dtop="docker top"
alias dunpause="docker unpause"
alias dversion="docker version"
alias dwait="docker wait"
alias drun="docker run"

# customized aliases
# list all docker processes included stop containers.
alias dpa="docker ps -a"
# list all untagged images (dangling)
alias dangline="docker images -f "dangling=true" -q"
# get dockerfile from image 
# Usages: dfimage <image> [-f], example: dfimage nginx
alias dfimage="docker run -v /var/run/docker.sock:/var/run/docker.sock centurylink/dockerfile-from-image"
